- name: Check the facts and install nginx if RedHat
  hosts: local
  connection: local
  become: yes

  tasks:
    - name: Install nginx if RedHat
      ansible.builtin.yum:
        name: nginx
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Print message if not RedHat
      ansible.builtin.debug:
        msg: "This is not a RedHat-based system, skipping nginx installation."
      when: ansible_os_family != "RedHat"
