- name: loops
  hosts: local
  connection: local
  tasks:
    - name: print name
      ansible.builtin.debug:
        msg: "Hello {{ item }}"
      loop:
        - madhan
        - anil
        - thulasiram
        - nethaji
