- name: loops
  hosts: local
  connection: local
  become: yes
  gather_facts: no

  tasks:
    - name: install packages
      ansible.builtin.package:
        name: "{{ item.name}}"
        state: "{{ item.state}}"
      loop:
      - {name: "nginx", state: "latest"}
      - {name: "mysql", state: "latest"}
      - {name: "zip", state: "latest"}
